### ISSUE TITLE
Trying to run locally

### ISSUE THREAD

**Issue by ianis58** [Qomaa/Pixmap#1]
Hi @Qomaa ,

I'm currently trying to run Pixmap locally to play with it.
I managed to run the server, connection to mongodb is ok, and messages are saved in "messages" collection in mongodb when events on the message or website fields are triggered.

I don't understand how are applied edits to the datas in mongodb in the "map" collection when we send some iota for changing a pixel.

I assume that there might be a server-side running task, checking at some frequency the datas on the page https://thetangle.org/address/XLQREBKIDVHUXGMUUKUXTXDVSAXIBUVKXPDCP9IJKWHHSGYVJUMQPAHWMQCCNAWSYZXBXCHHWVSFKXPBXBCGYHMCUC

Thanks !

**Comment by Qomaa** [comment]
Glad to hear your interest in iota.Show. There is indeed an additional Server App. You can find its source at https://github.com/Qomaa/Pixmap.IOTA

**Comment by ianis58** [comment]
Oh nice ! Thank you I will try it :)
